#!/usr/bin/env python
# coding: utf-8

"""
ConnectorsApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
from __future__ import absolute_import

import sys
import os

# python 2 and python 3 compatibility library
from six import iteritems

from ..util import remove_none

from ..swagger import ApiClient

class ConnectorsApi(object):

    def __init__(self, api_client):
        self.api_client = api_client
    
    def connectors_list_get(self, **kwargs):
        """
        List of Connectors
        Returns a list of all available connectors. A connector pulls data from other data providers using their API or a screenscraper.

        
        :return: list[Connector]
        """
        
        all_params = []

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method connectors_list_get" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/connectors/list'.replace('{format}', 'json')
        method = 'GET'

        path_params = remove_none(dict())
        query_params = remove_none(dict())
        header_params = remove_none(dict())
        form_params = remove_none(dict())
        files = remove_none(dict())
        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = ApiClient.select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = ApiClient.select_header_content_type([])

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response='list[Connector]')
        
        return response
        
    def connectors_connector_connect_get(self, connector, **kwargs):
        """
        Obtain a token from 3rd party data source
        Attempt to obtain a token from the data provider, store it in the database. With this, the connector to continue to obtain new user data until the token is revoked.

        :param str connector: Lowercase system name of the source application or device. Get a list of available connectors from the /connectors/list endpoint. (required)
        
        :return: None
        """
        
        # verify the required parameter 'connector' is set
        if connector is None:
            raise ValueError("Missing the required parameter `connector` when calling `connectors_connector_connect_get`")
        
        all_params = ['connector']

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method connectors_connector_connect_get" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/connectors/{connector}/connect'.replace('{format}', 'json')
        method = 'GET'

        path_params = remove_none(dict(connector=params.get('connector')))
        query_params = remove_none(dict())
        header_params = remove_none(dict())
        form_params = remove_none(dict())
        files = remove_none(dict())
        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = ApiClient.select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = ApiClient.select_header_content_type([])

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response=None)
        
    def connectors_connector_connect_instructions_get(self, connector, **kwargs):
        """
        Get connection parameters
        Returns instructions that describe what parameters and endpoint to use to connect to the given data provider.

        :param str connector: Lowercase system name of the source application or device. Get a list of available connectors from the /connectors/list endpoint. (required)
        
        :return: None
        """
        
        # verify the required parameter 'connector' is set
        if connector is None:
            raise ValueError("Missing the required parameter `connector` when calling `connectors_connector_connect_instructions_get`")
        
        all_params = ['connector']

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method connectors_connector_connect_instructions_get" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/connectors/{connector}/connectInstructions'.replace('{format}', 'json')
        method = 'GET'

        path_params = remove_none(dict(connector=params.get('connector')))
        query_params = remove_none(dict())
        header_params = remove_none(dict())
        form_params = remove_none(dict())
        files = remove_none(dict())
        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = ApiClient.select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = ApiClient.select_header_content_type([])

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response=None)
        
    def connectors_connector_disconnect_get(self, connector, **kwargs):
        """
        Delete stored connection info
        The disconnect method deletes any stored tokens or connection information from the connectors database.

        :param str connector: Lowercase system name of the source application or device. Get a list of available connectors from the /connectors/list endpoint. (required)
        
        :return: None
        """
        
        # verify the required parameter 'connector' is set
        if connector is None:
            raise ValueError("Missing the required parameter `connector` when calling `connectors_connector_disconnect_get`")
        
        all_params = ['connector']

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method connectors_connector_disconnect_get" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/connectors/{connector}/disconnect'.replace('{format}', 'json')
        method = 'GET'

        path_params = remove_none(dict(connector=params.get('connector')))
        query_params = remove_none(dict())
        header_params = remove_none(dict())
        form_params = remove_none(dict())
        files = remove_none(dict())
        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = ApiClient.select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = ApiClient.select_header_content_type([])

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response=None)
        
    def connectors_connector_info_get(self, connector, **kwargs):
        """
        Get connector info for user
        Returns information about the connector such as the connector id, whether or not is connected for this user (i.e. we have a token or credentials), and its update history for the user.

        :param str connector: Lowercase system name of the source application or device. Get a list of available connectors from the /connectors/list endpoint. (required)
        
        :return: None
        """
        
        # verify the required parameter 'connector' is set
        if connector is None:
            raise ValueError("Missing the required parameter `connector` when calling `connectors_connector_info_get`")
        
        all_params = ['connector']

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method connectors_connector_info_get" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/connectors/{connector}/info'.replace('{format}', 'json')
        method = 'GET'

        path_params = remove_none(dict(connector=params.get('connector')))
        query_params = remove_none(dict())
        header_params = remove_none(dict())
        form_params = remove_none(dict())
        files = remove_none(dict())
        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = ApiClient.select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = ApiClient.select_header_content_type([])

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response=None)
        
    def connectors_connector_update_get(self, connector, **kwargs):
        """
        Sync with data source
        The update method tells the QM Connector Framework to check with the data provider (such as Fitbit or MyFitnessPal) and retrieve any new measurements available.

        :param str connector: Lowercase system name of the source application or device (required)
        
        :return: None
        """
        
        # verify the required parameter 'connector' is set
        if connector is None:
            raise ValueError("Missing the required parameter `connector` when calling `connectors_connector_update_get`")
        
        all_params = ['connector']

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method connectors_connector_update_get" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/connectors/{connector}/update'.replace('{format}', 'json')
        method = 'GET'

        path_params = remove_none(dict(connector=params.get('connector')))
        query_params = remove_none(dict())
        header_params = remove_none(dict())
        form_params = remove_none(dict())
        files = remove_none(dict())
        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = ApiClient.select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = ApiClient.select_header_content_type([])

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response=None)
        









