#!/usr/bin/env python
# coding: utf-8

"""
PairsApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
from __future__ import absolute_import

import sys
import os

# python 2 and python 3 compatibility library
from six import iteritems

from ..util import remove_none

from ..swagger import ApiClient

class PairsApi(object):

    def __init__(self, api_client):
        self.api_client = api_client
    
    def pairs_get(self, cause, effect, **kwargs):
        """
        Get pairs
        Pairs cause measurements with effect measurements grouped over the duration of action after the onset delay.

        :param str cause: Original variable name for the explanatory or independent variable (required)
        :param str cause_source: Name of data source that the cause measurements should come from 
        :param str cause_unit: Abbreviated name for the unit cause measurements to be returned in 
        :param str delay: Delay before onset of action (in seconds) from the cause variable settings. 
        :param str duration: Duration of action (in seconds) from the cause variable settings. 
        :param str effect: Original variable name for the outcome or dependent variable (required)
        :param str effect_source: Name of data source that the effectmeasurements should come from 
        :param str effect_unit: Abbreviated name for the unit effect measurements to be returned in 
        :param str end_time: The most recent date (in epoch time) for which we should return measurements 
        :param str start_time: The earliest date (in epoch time) for which we should return measurements 
        
        :return: None
        """
        
        # verify the required parameter 'cause' is set
        if cause is None:
            raise ValueError("Missing the required parameter `cause` when calling `pairs_get`")
        
        # verify the required parameter 'effect' is set
        if effect is None:
            raise ValueError("Missing the required parameter `effect` when calling `pairs_get`")
        
        all_params = ['cause', 'cause_source', 'cause_unit', 'delay', 'duration', 'effect', 'effect_source', 'effect_unit', 'end_time', 'start_time']

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method pairs_get" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/pairs'.replace('{format}', 'json')
        method = 'GET'

        path_params = remove_none(dict())
        query_params = remove_none(dict(cause=params.get('cause'), causeSource=params.get('cause_source'), causeUnit=params.get('cause_unit'), delay=params.get('delay'), duration=params.get('duration'), effect=params.get('effect'), effectSource=params.get('effect_source'), effectUnit=params.get('effect_unit'), endTime=params.get('end_time'), startTime=params.get('start_time')))
        header_params = remove_none(dict())
        form_params = remove_none(dict())
        files = remove_none(dict())
        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = ApiClient.select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = ApiClient.select_header_content_type([])

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response=None)
        









