# coding: utf-8

"""
    QuantiModo

    QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """ AuthenticationApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.authentication_api.AuthenticationApi()

    def tearDown(self):
        pass

    def test_v2_auth_social_authorize_code_get(self):
        """
        Test case for v2_auth_social_authorize_code_get

        Second Step in Social Authentication flow with JWT Token
        """
        pass

    def test_v2_auth_social_authorize_token_get(self):
        """
        Test case for v2_auth_social_authorize_token_get

        Native Social Authentication
        """
        pass

    def test_v2_auth_social_login_get(self):
        """
        Test case for v2_auth_social_login_get

        First Setp in Social Authentication flow with JWT Token
        """
        pass

    def test_v2_oauth2_access_token_get(self):
        """
        Test case for v2_oauth2_access_token_get

        Get a user access token
        """
        pass

    def test_v2_oauth_authorize_get(self):
        """
        Test case for v2_oauth_authorize_get

        Request Authorization Code
        """
        pass


if __name__ == '__main__':
    unittest.main()
