#!/usr/bin/env python
# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from pprint import pformat
from six import iteritems


class User(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Swagger model

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'wp_id': 'int',
            'display_name': 'str',
            'login_name': 'str',
            'email': 'str',
            'token': 'str',
            'administrator': 'bool'
        }

        self.attribute_map = {
            'id': 'id',
            'wp_id': 'wpId',
            'display_name': 'displayName',
            'login_name': 'loginName',
            'email': 'email',
            'token': 'token',
            'administrator': 'administrator'
        }

        self._id = None    # User id
        self._wp_id = None    # Wordpress user id
        self._display_name = None    # User display name
        self._login_name = None    # User login name
        self._email = None    # User email
        self._token = None    # User token
        self._administrator = None    # Is user administrator

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, id):
        self._id = id

    @property
    def wp_id(self):
        return self._wp_id

    @wp_id.setter
    def wp_id(self, wp_id):
        self._wp_id = wp_id

    @property
    def display_name(self):
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        self._display_name = display_name

    @property
    def login_name(self):
        return self._login_name

    @login_name.setter
    def login_name(self, login_name):
        self._login_name = login_name

    @property
    def email(self):
        return self._email

    @email.setter
    def email(self, email):
        self._email = email

    @property
    def token(self):
        return self._token

    @token.setter
    def token(self, token):
        self._token = token

    @property
    def administrator(self):
        return self._administrator

    @administrator.setter
    def administrator(self, administrator):
        self._administrator = administrator

    def to_dict(self):
        """
        Return model properties dict
        """
        result = {}

        for name, prop in iteritems(self.__dict__):
            if name == "attribute_map" or name == "swagger_types":
                continue
            if isinstance(prop, list):
                result[name[1:]] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    prop
                ))
            elif hasattr(prop, "to_dict"):
                result[name[1:]] = prop.to_dict()
            else:
                result[name[1:]] = prop

        return result

    def to_str(self):
        """
        Return model properties str
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()
