#!/usr/bin/env python
# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class Permission(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        """
        Swagger model

        :param dict swaggerTypes: The key is attribute name and the value is attribute type.
        :param dict attributeMap: The key is attribute name and the value is json key in definition.
        """
        self.swagger_types = {
            'target': 'int',
            'variable_name': 'str',
            'min_timestamp': 'int',
            'max_timestamp': 'int',
            'min_time_of_day': 'int',
            'max_time_of_day': 'int',
            'week': 'str'
        }

        self.attribute_map = {
            'target': 'target',
            'variable_name': 'variableName',
            'min_timestamp': 'min_timestamp',
            'max_timestamp': 'max_timestamp',
            'min_time_of_day': 'min_time_of_day',
            'max_time_of_day': 'max_time_of_day',
            'week': 'week'
        }
        
        # Grant permission to target user or public so they may access measurements within the given parameters. TODO: Rename target to something more intuitive.
        self.target = None  # int
        
        # ORIGINAL Variable name
        self.variable_name = None  # str
        
        # Earliest time when measurements will be accessible in epoch seconds
        self.min_timestamp = None  # int
        
        # Latest time when measurements will be accessible in epoch seconds
        self.max_timestamp = None  # int
        
        # Earliest time of day when measurements will be accessible in epoch seconds
        self.min_time_of_day = None  # int
        
        # Latest time of day when measurements will be accessible in epoch seconds
        self.max_time_of_day = None  # int
        
        # Maybe specifies if only weekday measurements should be accessible
        self.week = None  # str
        

    def __repr__(self):
        properties = []
        for p in self.__dict__:
            if p != 'swaggerTypes' and p != 'attributeMap':
                properties.append('{prop}={val!r}'.format(prop=p, val=self.__dict__[p]))

        return '<{name} {props}>'.format(name=__name__, props=' '.join(properties))


