# coding: utf-8

"""
    QuantiModo

    QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ConnectorInstruction(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, url=None, parameters=None, use_popup=None):
        """
        ConnectorInstruction - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'url': 'str',
            'parameters': 'list[str]',
            'use_popup': 'bool'
        }

        self.attribute_map = {
            'url': 'url',
            'parameters': 'parameters',
            'use_popup': 'usePopup'
        }

        self._url = url
        self._parameters = parameters
        self._use_popup = use_popup


    @property
    def url(self):
        """
        Gets the url of this ConnectorInstruction.
        url

        :return: The url of this ConnectorInstruction.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this ConnectorInstruction.
        url

        :param url: The url of this ConnectorInstruction.
        :type: str
        """

        self._url = url

    @property
    def parameters(self):
        """
        Gets the parameters of this ConnectorInstruction.
        parameters array

        :return: The parameters of this ConnectorInstruction.
        :rtype: list[str]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """
        Sets the parameters of this ConnectorInstruction.
        parameters array

        :param parameters: The parameters of this ConnectorInstruction.
        :type: list[str]
        """

        self._parameters = parameters

    @property
    def use_popup(self):
        """
        Gets the use_popup of this ConnectorInstruction.
        usePopup

        :return: The use_popup of this ConnectorInstruction.
        :rtype: bool
        """
        return self._use_popup

    @use_popup.setter
    def use_popup(self, use_popup):
        """
        Sets the use_popup of this ConnectorInstruction.
        usePopup

        :param use_popup: The use_popup of this ConnectorInstruction.
        :type: bool
        """

        self._use_popup = use_popup

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
