#!/usr/bin/env python
# coding: utf-8

"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class User(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        """
        Swagger model

        :param dict swaggerTypes: The key is attribute name and the value is attribute type.
        :param dict attributeMap: The key is attribute name and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'wp_id': 'int',
            'display_name': 'str',
            'login_name': 'str',
            'email': 'str',
            'token': 'str',
            'administrator': 'bool'
        }

        self.attribute_map = {
            'id': 'id',
            'wp_id': 'wpId',
            'display_name': 'displayName',
            'login_name': 'loginName',
            'email': 'email',
            'token': 'token',
            'administrator': 'administrator'
        }
        
        # User id
        self.id = None  # int
        
        # Wordpress user id
        self.wp_id = None  # int
        
        # User display name
        self.display_name = None  # str
        
        # User login name
        self.login_name = None  # str
        
        # User email
        self.email = None  # str
        
        # User token
        self.token = None  # str
        
        # Is user administrator
        self.administrator = None  # bool
        

    def __repr__(self):
        properties = []
        for p in self.__dict__:
            if p != 'swaggerTypes' and p != 'attributeMap':
                properties.append('{prop}={val!r}'.format(prop=p, val=self.__dict__[p]))

        return '<{name} {props}>'.format(name=__name__, props=' '.join(properties))


